language: c

sudo: false

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

script: autoconf && ./configure && make && make check && (cd test-dev; autoconf && ./configure && make) && make -f Makefile.lite

matrix:
  include:
    # Linux distributions

    - os: linux
      dist: focal
      addons:
        apt:
          packages:
            - unrar

    - os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - unrar

    - os: linux
      dist: precise

    # mingw32 cross compilation

    - os: linux
      compiler: x86_64-w64-mingw32-gcc
      script: autoconf && ./configure --host=x86_64-w64-mingw32 && make
      dist: focal
      addons:
        apt:
          packages:
            - gcc-mingw-w64-base
            - binutils-mingw-w64-x86-64
            - gcc-mingw-w64-x86-64
            - gcc-mingw-w64

    # windows with visual studio 2017, x86 and x64

    - os: windows
      language: c
      compiler: cl
      script:
        - cmd.exe //C 'C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat' x86 '&&' nmake -f Makefile.vc
        - cmd.exe //C 'C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat' x86 '&&' nmake -f Makefile.vc check
        - cmd.exe //C 'C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat' x86 '&&' cd test-dev '&&' nmake -f Makefile.vc

    - os: windows
      language: c
      compiler: cl
      script:
        - cmd.exe //C 'C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat' amd64 '&&' nmake -f Makefile.vc
        - cmd.exe //C 'C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat' amd64 '&&' nmake -f Makefile.vc check
        - cmd.exe //C 'C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat' amd64 '&&' cd test-dev '&&' nmake -f Makefile.vc

    # clang sanitizers

    - os: linux
      dist: focal
      compiler: clang
      env: CFLAGS="-fsanitize=address" LDFLAGS="-fsanitize=address"
      script: autoconf && ./configure && make && make check && (cd test-dev; autoconf && ./configure && make)
      addons:
        apt:
          packages:
            - unrar

    - os: linux
      dist: focal
      compiler: clang
      env: CFLAGS="-fsanitize=memory" LDFLAGS="-fsanitize=memory"
      script: autoconf && ./configure && make && make check && (cd test-dev; autoconf && ./configure && make)
      addons:
        apt:
          packages:
            - unrar
