name: Emscripten build test

on:
  - pull_request
  - push

jobs:
  emscripten:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt update && sudo apt install autoconf
      - name: Install emscripten
        run: |
          cd ..
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
      - name: Create and run configure script
        run: |
          source ../emsdk/emsdk_env.sh
          autoreconf -iv
          emconfigure ./configure --enable-static --disable-shared
      - name: Build
        run: |
          source ../emsdk/emsdk_env.sh
          emmake make
      - name: Test build
        run: |
          source ../emsdk/emsdk_env.sh
          cd test
          emcc test.c ../src/md5.c -o test.js -O3 -Wall -I../include -I../src -L../lib/ --embed-file test.itz -lxmp
          node test.js
